# Generated by Django 5.0.14 on 2026-04-19 10:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_options_branch_address_branch_currency_and_more'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmodifier',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='itemvariant',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menucategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_categories', to='branches.branch'),
        ),
    ]
