# Generated by Django 5.0.14 on 2026-04-23 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branch_options_branch_address_branch_currency_and_more'),
        ('menu', '0002_alter_itemmodifier_options_alter_itemvariant_options_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Millilitres'), ('l', 'Litres'), ('pcs', 'Pieces')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='branches.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='organizations.organization')),
            ],
            options={
                'db_table': 'ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_stocks', to='branches.branch')),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='menu.menuitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_stocks', to='organizations.organization')),
            ],
            options={
                'db_table': 'item_stocks',
                'ordering': ['menu_item__name'],
            },
        ),
    ]
