# Generated by Django 5.0.14 on 2026-04-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_inventory_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('restock', 'Restock'), ('deduct', 'Deduct'), ('usage', 'Usage'), ('waste', 'Waste'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
